// AUTO-GENERATED by agentflow-gui build script — do not edit manually
// Regenerated each time 'gui' subcommand is invoked

import type { Component } from 'vue'
import GenericJsonRenderer from './GenericJsonRenderer.vue'

import HotelReservation from './hotel_reservation.vue'

export const EVENT_RENDERERS: Record<string, Component> = {
  "hotel.reservation": HotelReservation,
}

export { GenericJsonRenderer }

export function getRenderer(eventType: string): Component {
  return EVENT_RENDERERS[eventType] ?? GenericJsonRenderer
}
