import type { Component } from 'vue'
import GenericJsonRenderer from './GenericJsonRenderer.vue'

// Registry: event_type → Vue component
// Add custom renderers here (auto-generated by agentflow-gui build script)
export const EVENT_RENDERERS: Record<string, Component> = {}

export { GenericJsonRenderer }

export function getRenderer(eventType: string): Component {
  return EVENT_RENDERERS[eventType] ?? GenericJsonRenderer
}
